const actions = {
    ANSWER_QUESTION: 'ANSWERED_QUESTION',
    NEXT_QUESTION: 'MOVE_TO_NEXT_QUESTION',
    PREVIOUS_QUESTION: 'MOVE_TO_PREVIOUS_QUESTION',
    REMOVE_REDUX: 'REMOVE_REDUX',
    GET_RESULTS: 'GET_RESULTS',
}

export default actions;
